//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstCargoApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FirstCargoDbEntities : DbContext
    {
        public FirstCargoDbEntities()
            : base("name=FirstCargoDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIES> CATEGORIES { get; set; }
        public virtual DbSet<OTHERS> OTHERS { get; set; }
        public virtual DbSet<PACKAGES> PACKAGES { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<VEHICULES> VEHICULES { get; set; }
    }
}
