//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Ã„nderungen an dieser Datei fÃ¼hren mÃ¶glicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Ã„nderungen an dieser Datei werden Ã¼berschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstCargoApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Package
    {
        public int packageID { get; set; }
        [Display(Name = "PackageType", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "PackageTypeRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string packageType { get; set; }
        [Display(Name = "SenderName", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "SenderNameRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string senderName { get; set; }
        [Display(Name = "SenderAdress", ResourceType = typeof(ViewResources.Resource))]
        public string senderAdress { get; set; }
        [Display(Name = "SenderPhoneNumber", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "SenderPhoneNumberRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [RegularExpression("([0-9][0-9]*)", ErrorMessageResourceName = "DigitRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string senderPhoneNumber { get; set; }
        [Display(Name = "RecieverName", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "RecieverNameRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string recieverName { get; set; }
        [Display(Name = "RecieverAdress", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "RecieverAddressRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string recieverAdress { get; set; }
        [Display(Name = "RecieverPhoneNumber", ResourceType = typeof(ViewResources.Resource))]
        public string recieverPhoneNumber { get; set; }
        [Display(Name = "Destination", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "DestinationRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string destination { get; set; }
        [Display(Name = "Price", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "PriceRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [DataType(DataType.Currency)]
        public Nullable<decimal> price { get; set; }
        [Display(Name = "Paid", ResourceType = typeof(ViewResources.Resource))]
        public bool paid { get; set; }
        [Display(Name = "Weight", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "WeightRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        
        public Nullable<decimal> weight { get; set; }
        [Display(Name = "Height", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "HeightRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        
        public Nullable<decimal> height { get; set; }
        [Display(Name = "Length", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "LenghtRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        
        public Nullable<decimal> length { get; set; }
        [Display(Name = "Depth", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "DepthRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        
        public Nullable<decimal> depth { get; set; }
        [Display(Name = "ContentDescription", ResourceType = typeof(ViewResources.Resource))]
        [DataType(DataType.MultilineText)]
        public string contentDescription { get; set; }
        public int userID { get; set; }
        [Display(Name = "SenderEmail", ResourceType = typeof(ViewResources.Resource))]
        [EmailAddress(ErrorMessage = "EmailAddressRequired")]
        public string senderEmail { get; set; }
        [Display(Name = "RecieverEmail", ResourceType = typeof(ViewResources.Resource))]
        [EmailAddress(ErrorMessage = "EmailAddressRequired")]
        public string recieverEmail { get; set; }

        public string orderNumber { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<FirstCargoApp.Helper.Paid> paidTextID { get; set; }

        [Display(Name = "RestToPay", ResourceType = typeof(ViewResources.Resource))]
        [DataType(DataType.Currency)]
        [Required(ErrorMessageResourceName = "RestToPayRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public Nullable<decimal> paidRest { get; set; }


        [Display(Name = "Paid", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "PriceRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [DataType(DataType.Currency)]
        public Nullable<decimal> alreadyPaid { get; set; }
    }
}
