//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstCargoApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class USER
    {
        [Key]
        public int userID { get; set; }
        [Display(Name = "UserName", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "UserNameRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string userName { get; set; }
        [Display(Name = "UserFirstName", ResourceType = typeof(ViewResources.Resource))]
        public string userFirstName { get; set; }
        [Display(Name = "UserLastName", ResourceType = typeof(ViewResources.Resource))]
        public string userLastName { get; set; }
        [Display(Name = "DateOfBirth", ResourceType = typeof(ViewResources.Resource))]
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessageResourceName = "PasswordRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [Display(Name = "Password", ResourceType = typeof(ViewResources.Resource))]
        public string password { get; set; }
        [Display(Name = "IsAdmin", ResourceType = typeof(ViewResources.Resource))]
        public bool isAdmin { get; set; }
        [Display(Name = "CreatedDate", ResourceType = typeof(ViewResources.Resource))]
        public Nullable<System.DateTime> createdDate { get; set; }
        public string confirmationToken { get; set; }
        [Display(Name = "IsConfirmed", ResourceType = typeof(ViewResources.Resource))]
        public bool isConfirmed { get; set; }
        public Nullable<System.DateTime> lastPasstWortFailuresDates { get; set; }
        public Nullable<System.DateTime> passwordFailuresDateSinceLastSuccess { get; set; }
        [Display(Name = "PasswordChangedDates", ResourceType = typeof(ViewResources.Resource))]
        public Nullable<System.DateTime> passwordChangedDates { get; set; }
        public string passwordSalt { get; set; }
        public string passwordVerificationToken { get; set; }
        public Nullable<System.DateTime> passwordVerificationTokenExprirationDate { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessageResourceName = "OldPasswordRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [Display(Name = "OldPassword", ResourceType = typeof(ViewResources.Resource))]
        public string oldPassword { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessageResourceName = "ConfirmPasswordRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        //[Compare("NewPassword", ErrorMessage = "Das neue Kennwort stimmt nicht mit dem Bestätigungskennwort überein.")]
        [Display(Name = "ConfirmPassword", ResourceType = typeof(ViewResources.Resource))]
        public string confirmPassword { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessageResourceName = "NewPasswordRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [Display(Name = "NewPassword", ResourceType = typeof(ViewResources.Resource))]
        public string newPassword { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessageResourceName = "EmailRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [Display(Name = "Email", ResourceType = typeof(ViewResources.Resource))]
        public string email { get; set; }
    }
}
