//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstCargoApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
     
    public partial class Vehicule
    {
        public int vehiculeID { get; set; }
        [Display(Name = "SenderName", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "SenderNameRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string senderName { get; set; }
        [Display(Name = "SenderAdress", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "SenderAdressRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string senderAdress { get; set; }
        [Display(Name = "SenderPhoneNumber", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "SenderPhoneNumberRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [RegularExpression("([0-9][0-9]*)", ErrorMessageResourceName = "DigitRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string senderPhoneNumber { get; set; }
        [Display(Name = "RecieverName", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "RecieverNameRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string recieverName { get; set; }
        [Display(Name = "RecieverAdress", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "RecieverAddressRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string recieverAdress { get; set; }
        [Display(Name = "RecieverPhoneNumber", ResourceType = typeof(ViewResources.Resource))]
        [RegularExpression("([0-9][0-9]*)", ErrorMessageResourceName = "DigitRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string recieverPhoneNumber { get; set; }
        [Display(Name = "Destination", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "DestinationRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string destination { get; set; }
        [Display(Name = "Price", ResourceType = typeof(ViewResources.Resource))]
        [DataType(DataType.Currency)]
        [Required(ErrorMessageResourceName = "PriceRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public Nullable<decimal> price { get; set; }
        [Display(Name = "Paid", ResourceType = typeof(ViewResources.Resource))]
        public bool paid { get; set; }
        [Display(Name = "Weight", ResourceType = typeof(ViewResources.Resource))]
        [RegularExpression(@"[0-9]{0,}\.[0-9]{2}", ErrorMessage = "error Message")] 
        public Nullable<decimal> weight { get; set; }
        [Display(Name = "Height", ResourceType = typeof(ViewResources.Resource))]
        [RegularExpression(@"[0-9]{0,}\.[0-9]{2}", ErrorMessage = "error Message")] 
        public Nullable<decimal> height { get; set; }
        [Display(Name = "Length", ResourceType = typeof(ViewResources.Resource))]
        [RegularExpression(@"[0-9]{0,}\.[0-9]{2}", ErrorMessage = "error Message")] 
        public Nullable<decimal> length { get; set; }
        [Display(Name = "Depth", ResourceType = typeof(ViewResources.Resource))]
        [RegularExpression(@"[0-9]{0,}\.[0-9]{2}", ErrorMessage = "error Message")] 
        public Nullable<decimal> depth { get; set; }
        public Nullable<int> userID { get; set; }
        [Display(Name = "VehiculeType", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "VehiculeTypeRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string vehiculeType { get; set; }
        [Display(Name = "FrameNumber", ResourceType = typeof(ViewResources.Resource))]
        [Required(ErrorMessageResourceName = "FrameNumberRequired", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [StringLength(17, ErrorMessageResourceName = "FrameNumberLength", MinimumLength = 17, ErrorMessageResourceType = typeof(ViewResources.Resource))]
        [RegularExpression(@"^[a-zA-Z0-9]*$", ErrorMessageResourceName = "FrameNumberPattern", ErrorMessageResourceType = typeof(ViewResources.Resource))]
        public string frameNumber { get; set; }
        [Display(Name = "SenderEmail", ResourceType = typeof(ViewResources.Resource))]
        [EmailAddress(ErrorMessage = "EmailAddressRequired")]
        public string senderEmail { get; set; }
        [Display(Name = "RecieverEmail", ResourceType = typeof(ViewResources.Resource))]
        [EmailAddress(ErrorMessage = "EmailAddressRequired")]
        public string recieverEmail { get; set; }
        public string orderNumber { get; set; }

    }
}


