//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstCargoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULES: CATEGORIES
    {
        public int vehiculeID { get; set; }
        public string vehiculeType { get; set; }
        public string frameNumber { get; set; }
        public Nullable<int> categoryID { get; set; }
    
        public virtual CATEGORIES CATEGORIES { get; set; }
    }
}
